= Logging HTTP Headers

This library provides a servlet filter and a tomcat valve which populate slf4j MDC with data from HTTP request.
Both filter and valve have the same functionality, and provided together for better flexibility (some apps will prefer
the filter, while the other will prefer the valve).

The next fields are populated:

|===
|Name|MDC|Comment

|Remote IP address|httpRemoteAddr|
|Remote port|httpRemotePort|
|User agent|httpUserAgent|From User-Agent header
|Authenticated user|httpRemoteUser|The user associated with current http request, if any
|X-Forwarded-For header|httpForwardedFor|This header is usually set by proxies when relay a request
|===

== Usage

=== Static

To use the lib statically it needs to be added to a config file either in web app or in tomcat.

==== Filter

The filter needs to be defined in the web.xml file of the web app that wishes to use it. For example:

[source,xml]
----
    <filter>
        <filter-name>httpHeadersMDCFilter</filter-name>
        <filter-class>org.talend.daikon.logging.http.headers.HttpHeadersMDCFilter</filter-class>
        <init-param>
            <param-name>replaceRemoteAddrWithForwardedFor</param-name>
            <param-value>false</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>httpHeadersMDCFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
----

==== Valve

The valve needs to be defined in tomcat's `conf/server.xml` file, under Engine section (it will be applied to
all web apps deployed on this tomcat deployment). Additionally, the jar file with the valve (and possibly
other dependencies, like `slf4j-api`) needs to be copied into `tomcat/lib` directory.

NOTE: This approach is not recommended, as there may be class-loading issues with slf4j.

[source,xml]
----
    <Valve className="org.talend.daikon.logging.http.headers.HttpHeadersMDCValve"
           replaceRemoteAddrWithForwardedFor="false" />
----

=== Spring Boot

With spring boot it's possible to register filter or valve programmatically. For this it's necessary
to define corresponding bean (see below) in a spring configuration class.

==== Filter

To define the filter dynamically:

[source,java]
----
    @Bean
    public FilterRegistrationBean filterRegistrationBean() {
        FilterRegistrationBean regBean = new FilterRegistrationBean();

        HttpHeadersMDCFilter filtr = new HttpHeadersMDCFilter();
        filtr.setReplaceRemoteAddrWithForwardedFor(false);

        regBean.setFilter(filtr);
        regBean.setOrder(SecurityProperties.DEFAULT_FILTER_ORDER + 1);

        return regBean;
    }
----

==== Valve

To define the valve dynamically:

[source,java]
----
    @Bean
    public EmbeddedServletContainerCustomizer tomcatContextCustomizer() {
        HttpHeadersMDCValve valv = new HttpHeadersMDCValve();
        valv.setReplaceRemoteAddrWithForwardedFor(false);

        return (x -> {
            if (x instanceof TomcatEmbeddedServletContainerFactory) {
                ((TomcatEmbeddedServletContainerFactory) x).addContextCustomizers(y -> {
                    y.getPipeline().addValve(valv);
                });
            }
        });
    }
----

=== Configuration

The next table lists available configuration properties.

|===
|Property|Filter/Valve|Optionial?|Description

|replaceRemoteAddrWithForwardedFor|Both|Yes (default: false)|Substitutes remote IP address with the value
in X-Forwarded-For header (if available)
|===
